-- 코드를 입력하세요
SELECT T1.PRODUCT_CODE
     , SUM(T1.PRICE * T2.SALES_AMOUNT) AS "SALES"
  FROM PRODUCT T1
 INNER JOIN OFFLINE_SALE T2 ON (T1.PRODUCT_ID = T2.PRODUCT_ID)
 GROUP BY T1.PRODUCT_CODE
 ORDER BY SALES DESC
     , T1.PRODUCT_CODE ASC;