-- 코드를 입력하세요
SELECT T1.BOOK_ID
     , T2.AUTHOR_NAME
     , DATE_FORMAT(T1.PUBLISHED_DATE, '%Y-%m-%d') AS "PUBLISHED_DATE"
  FROM BOOK T1
 INNER JOIN AUTHOR T2 ON (T1.AUTHOR_ID = T2.AUTHOR_ID)
 WHERE T1.CATEGORY IN ('경제')
 ORDER BY PUBLISHED_DATE ASC;